#!/bin/bash

read -p "How old are you: " age


case $age in
[0-4])
	echo "To young for school"
	;;
5)
	echo "Go to Kindergarten"
	;;
[6-9]|1[0-8])
	grade=$((age-5))
	echo "Go to grade $grade"
	;;
*)
	echo "Too old for school"
	;;
esac

##Ternary operations

echo "Your age is $age"
can_vote=0

((age>=18? (can_vote=1):(can_vote=0) ))

echo "Can Vote: $can_vote"


