#!/bin/bash

#read information from the user, p pumped with string
read -p "What is your name? " name

echo "Hello $name"

read -p "How old are you " age

echo "You are $age years old!"
if [ $age -ge 16 ]
then
	echo "You can drive"
elif [ $age -eq 15 ]
then
	echo "You can drive next year"
else
	echo "You cannot drive"
fi
