#!/usr/bin/env python

import os
import numpy as np

LEF = BOT = 0.
RIG = TOP = 5.
ERR = 1.E-3
C1 = 0.52
C2 = 0.48

def getValue(x,y):
	cmd = "./obj_func"+" "+str(x)+" "+str(y)
	return float(os.popen(cmd).read())

def optimX(y):
	r = RIG
	l = LEF
	while(r-l >= ERR):
		m1 = l*C1 + r*C2
		m2 = l*C2 + r*C1
		if(getValue(m1,y) > getValue(m2,y)):
			l = m1;
		else:
			r = m2;
	return (l+r)/2.

def optim():
	t = TOP
	b = BOT
	while(t-b >= ERR):
		n1 = b*C1 + t*C2
		n2 = b*C2 + t*C1
		if(getValue(optimX(n1),n1) > getValue(optimX(n2),n2)):
			b = n1
		else:
			t = n2
	y = (b+t)/2.
	x = optimX(y)
	ans = getValue(x,y)
	return x,y,ans

x,y,ans = optim()
print "Find minimum: ",x,y,ans
